server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/AllanCruzX/microservice-repo
          search-paths: fornecedor          
        